### ISSUE TITLE
missing git version tag

### ISSUE THREAD

**Issue by kloczek** [chrisjsewell/sphinx-pyscript#1]
https://pypi.org/project/sphinx_pyscript/ shows that lates version is 0.1.0 however here there is no any verison tags.
BTW looks like "Home" link on https://pypi.org/project/sphinx_pyscript/ is broken.

**Comment by kloczek** [comment]
gentle ping .. 🤔

**Comment by kloczek** [comment]
Thank you 👍

**Comment by chrisjsewell** [comment]
no worries 😄
